name: Demo CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Push file from local to server
    - run:  cd /var/www/democicd
    - run:  git pull origin master
    - run:  git status
