name: Demo CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      BUILD_FOLDER: /var/www/democicd
    steps:
      - uses: actions/checkout@v2
