name: Demo CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: democicd
    
jobs:
  build:
    runs-on: self-hosted
      
    steps:
      - uses: actions/checkout@v2
