name: Demo CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: /var/www/democicd
    
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
